# Generated by Django 5.1.5 on 2025-02-06 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LocalLibrary', '0003_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
